version: '2'
services:
    oauthdemo-app:
        image: oauthdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://oauthdemo-mysql:3306/oauthdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=oauthdemo-elasticsearch:9300
        ports:
            - 8080:8080
    oauthdemo-mysql:
        extends:
            file: mysql.yml
            service: oauthdemo-mysql
    oauthdemo-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: oauthdemo-elasticsearch
